language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - pypy
env:
  - WTFORMS=WTForms==1.0.5
  - WTFORMS=https://github.com/wtforms/wtforms/archive/wtforms2.zip
install:
  - pip install $WTFORMS
  - pip install -e ".[test]"
script:
  - py.test
